### ISSUE TITLE
Create GitHub action for junit-to-ctrf

### ISSUE THREAD

**Issue by jonavos** [ctrf-io/junit-to-ctrf#11]
My workflow is currently:

```
- name: Convert reports to CTRF
  if: always()
  run: |
    mkdir -p build/ctrf
    for i in app/build/test-results/**/TEST-*.xml; do
      cp "$i" build/ctrf/
    done
    for i in library/build/test-results/**/TEST-*.xml; do
      cp "$i" build/ctrf/
    done
    for i in build/ctrf/*.xml; do
      npx junit-to-ctrf "$i" -o "${i%.xml}.json"
    done

- name: Merge CTRF reports
  if: always()
  run: |
    npx ctrf merge build/ctrf --output merged-ctrf-report.json --keep-reports

- name: Publish CTRF Test Report
  if: always()
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: 'build/ctrf/merged-ctrf-report.json'
    template-path: '.github/test-report.hbs'
    custom-report: true
    pull-request: true
    overwrite-comment: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It would be nice if I could invoke an action to complete the first two steps. It would be _really_ nice if I could invoke a single action to complete all three.

Thanks

**Comment by Rayvhiz** [comment]
I agree, a single action would be splendid.

**Comment by Ma11hewThomas** [comment]
Thanks for sharing your use case, this is really useful. I’m building something that will achieve what you need - in the meantime the github test reporter can handle a glob pattern for report-path - so you might be able to remove the merge stage

**Comment by Ma11hewThomas** [comment]
it's possible to do all three now, use a glob pattern for your junit reports

```yaml
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: './ctrf/*.xml'
    integrations-config: |
      {
        "junit-to-ctrf": {
          "enabled": true,
          "action": "convert"
        }
      }
  if: always()
```

https://github.com/ctrf-io/github-test-reporter/blob/main/docs/integrations.md#junit-to-ctrf-integration
